function TokenContainer(){
    this.token = {
        "token" : -1,
        "userId" : -1
    };
}

var ChatConstants = {
    "CHAT_READER_DELAY" : 1500
};

var EventBusMessages = {
    "UPDATE_APPLICATION_VIEW": 'UPDATE_APPLICATION_VIEW',

    "USER_LOGGED_IN" : 'USER_LOGGED_IN',
    "LOGIN_USER": 'LOGIN_USER',
    "SHOW_LOGIN_ERROR_MESSAGE": 'SHOW_LOGIN_ERROR_MESSAGE',

    "CHAT_LOADED": 'CHAT_LOADED',
    "USER_PROFILE_UPDATED" : 'USER_PROFILE_UPDATED',
    "CHAT_ROOM_LIST_UPDATED" : 'CHAT_ROOM_LIST_UPDATED',
    "JOINED_CHAT_ROOM_LIST_UPDATED" : 'JOINED_CHAT_ROOM_LIST_UPDATED',

    "JOIN_CHAT_ROOM" : 'JOIN_CHAT_ROOM',
    "JOINED_TO_CHAT_ROOM" : 'JOINED_TO_CHAT_ROOM',

    "CHAT_ROOM_SELECTED" : 'CHAT_ROOM_SELECTED',

    "USER_LOGGED_OUT": 'USER_LOGGED_OUT',
    "LOGOUT_USER": 'LOGOUT_USER',

    "UPDATE_CHAT_ROOM_USER_LIST" : 'UPDATE_CHAT_ROOM_USER_LIST',
    "CHAT_ROOM_USER_LIST_UPDATED" : 'CHAT_ROOM_USER_LIST_UPDATED',
    "UPDATE_CHAT_ROOM_MESSAGES" : 'UPDATE_CHAT_ROOM_MESSAGES',
    "CHAT_ROOM_MESSAGES_UPDATED" : 'CHAT_ROOM_MESSAGES_UPDATED',

    "SHOW_CHAT_ERROR_MESSAGE": 'SHOW_CHAT_ERROR_MESSAGE',
    "CHAT_ERROR_MESSAGE_SHOWED": 'CHAT_ERROR_MESSAGE_SHOWED',
    "SHOW_JOIN_CHAT_ROOM_ERROR_MESSAGE": 'SHOW_JOIN_CHAT_ROOM_ERROR_MESSAGE',

    "SEND_MESSAGE" : 'SEND_MESSAGE',

    "LEAVE_CHAT_ROOM": 'LEAVE_CHAT_ROOM',
    "CHAT_ROOM_LEFT": 'CHAT_ROOM_LEFT',

    "REGISTER_USER" : 'REGISTER_USER',
    "USER_REGISTERED" : 'USER_REGISTERED',
    "SHOW_REGISTER_ERROR_MESSAGE": 'SHOW_REGISTER_ERROR_MESSAGE',
    "SHOW_REGISTER_SUCCESS_MESSAGE": 'SHOW_REGISTER_SUCCESS_MESSAGE',
    "REGISTER_SUCCESS_MESSAGE_SHOWED": 'REGISTER_SUCCESS_MESSAGE_SHOWED'
};